## Configuration

In [ ]:

class Config():
    def __init__(self):
        self.db_name = "workout"
        self.max_FilesPerTrigger = 100

In [3]:
config = Config()
print(f"Database Name: {config.db_name}")

Database Name: workout

## Set Up

In [2]:
import os
def get_spark():
    """Get Spark session based on environment"""
    
    if "DATABRICKS_RUNTIME_VERSION" in os.environ:
        print("Running in Databricks environment")
        from databricks.sdk.runtime import spark
        return spark
    else:
        print("Running locally with Databricks Connect")
        from databricks.connect import DatabricksSession
        spark = (DatabricksSession
                .builder
                .profile("dev-free-edition")
                .serverless(True)
                .getOrCreate())
        return spark


spark = get_spark()
spark

Running locally with Databricks Connect

In [ ]:

class SetUp():
    def __init__(self,env):
        conf = Config()
        self.db_name = conf.db_name
        self.catalog = env
        self.initialized = False


    def create_db(self):
        print(f"Creating the database {self.catalog}.{self.db_name}...", end='')
        spark.sql(f"CREATE DATABASE IF NOT EXISTS {self.catalog}.{self.db_name}")
        spark.sql(f"USE {self.catalog}.{self.db_name}")
        self.initialized = True
        print("Done.")

In [10]:
setup = SetUp(env="dev")

In [ ]:
setup.create_db()

In [9]:
%sql

show databases in dev;

DataFrame[databaseName: string]

In [1]:

def get_secrets(name: str,  scope: str = "test", env: str = "local"):
    """Get secrets from environment variables or Databricks Secrets"""

    if env == "local":

        from dotenv import load_dotenv
        import os

        load_dotenv()
        return os.getenv(name)
    
    try:
        return dbutils.secrets.get(scope=scope, key=name)
    except Exception as e:
        print(f"Error getting secret {name} from scope {scope}: {e}")

    raise ValueError(f"Secret {name} not found in scope {scope}")

In [8]:
azure_storage_account = get_secrets("azure_storage_account")

In [3]:
catalog = "dev"

ingestion_db = "control"
ingestion_table = "ingest_table_registry"
bronze_db = "bronze_workout"


# spark.sql(f"CREATE DATABASE IF NOT EXISTS {catalog}.{ingestion_db};")

# spark.sql(f"CREATE DATABASE IF NOT EXISTS {catalog}.{bronze_db};")

In [3]:
query = f"""

CREATE TABLE IF NOT EXISTS {catalog}.{ingestion_db}.{ingestion_table} (
  table_id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  source_path STRING NOT NULL,
  source_format STRING DEFAULT 'parquet',
  header BOOLEAN DEFAULT TRUE,
  table_version INT DEFAULT 1,

  target_catalog STRING DEFAULT 'dev',
  target_schema STRING DEFAULT 'test',
  target_table STRING NOT NULL,
  write_mode STRING DEFAULT 'append'
      CHECK (write_mode IN ('append', 'merge', 'overwrite')),
  checkpoint_path STRING NOT NULL,
  merge_key ARRAY<STRING> DEFAULT ARRAY(),
  partition_by ARRAY<STRING> DEFAULT ARRAY(),
  enabled BOOLEAN DEFAULT TRUE,

 trigger_mode STRING DEFAULT 'availableNow'
    CHECK (trigger_mode IN ('availableNow', 'processingTime', 'continuous')),
  processing_time STRING DEFAULT '5 minutes',
  schema_evolution_mode STRING DEFAULT 'BACKWARD'
    CHECK (schema_evolution_mode IN ('BACKWARD', 'FORWARD', 'FULL', 'NONE')),
  
  expected_rows_per_day BIGINT,
  last_success TIMESTAMP,
  last_error STRING,
  consecutive_failures INT,
  last_run_duration_seconds INT,
  created_by STRING,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  updated_by STRING,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
TBLPROPERTIES (
  'delta.enableChangeDataFeed' = 'true',
  'delta.autoOptimize.autoCompact' = 'true',
  'delta.feature.allowColumnDefaults' = 'supported'
);

"""

In [17]:
spark.sql(query)

DataFrame[]

In [ ]:
insert_query = f"""

INSERT INTO {catalog}.{ingestion_db}.{ingestion_table} 
(source_path,                         source_format,header,table_version,target_catalog,target_schema,target_table,write_mode,checkpoint_path,merge_key,partition_by,enabled,trigger_mode,processing_time,schema_evolution_mode,expected_rows_per_day,last_success,last_error,consecutive_failures,last_run_duration_seconds,created_by,created_at,updated_by,updated_at)
VALUES 
('/Volumes/dev/bronze_workout/rw/bpm/', 'json', TRUE, 1, 'dev', 'bronze_workout', 'bpm', 'append', '/Volumes/dev/bronze_workout/checkpoints/', ARRAY(), ARRAY(), TRUE, 'availableNow', '5 minutes', 'BACKWARD', 1000000, NULL, NULL, 0, NULL, 'gaurav.thagunna', CURRENT_TIMESTAMP(), NULL, CURRENT_TIMESTAMP());

"""

spark.sql(insert_query)

DataFrame[num_affected_rows: bigint, num_inserted_rows: bigint]

In [4]:
configs = spark.sql(f"select * from {catalog}.{ingestion_db}.{ingestion_table}")
configs.show(truncate=False)

+--------+-------------------------------------------+-------------+------+-------------+--------------+--------------+------------+----------+----------------------------------------+---------+------------+-------+------------+---------------+---------------------+---------------------+------------+----------+--------------------+-------------------------+---------------+--------------------------+----------+--------------------------+
|table_id|source_path                                |source_format|header|table_version|target_catalog|target_schema |target_table|write_mode|checkpoint_path                         |merge_key|partition_by|enabled|trigger_mode|processing_time|schema_evolution_mode|expected_rows_per_day|last_success|last_error|consecutive_failures|last_run_duration_seconds|created_by     |created_at                |updated_by|updated_at                |
+--------+-------------------------------------------+-------------+------+-------------+--------------+--------------+------------+----------+----------------------------------------+---------+------------+-------+------------+---------------+---------------------+---------------------+------------+----------+--------------------+-------------------------+---------------+--------------------------+----------+--------------------------+
|1       |/Volumes/dev/bronze_workout/rw/dataset/bpm/|json         |true  |1            |dev           |bronze_workout|bpm         |append    |/Volumes/dev/bronze_workout/checkpoints/|[]       |[]          |true   |availableNow|5 minutes      |BACKWARD             |1000000              |NULL        |NULL      |0                   |NULL                     |gaurav.thagunna|2026-01-27 11:52:40.169692|NULL      |2026-01-27 11:52:40.169692|
+--------+-------------------------------------------+-------------+------+-------------+--------------+--------------+------------+----------+----------------------------------------+---------+------------+-------+------------+---------------+---------------------+---------------------+------------+----------+--------------------+-------------------------+---------------+--------------------------+----------+--------------------------+

In [5]:
configs_dict = configs.select("table_id","source_path","source_format","header","target_catalog","target_schema","table_version","target_table","write_mode","checkpoint_path","merge_key","partition_by","enabled","trigger_mode","processing_time","schema_evolution_mode").collect()[0].asDict()
configs_dict

{'table_id': 1,
 'source_path': '/Volumes/dev/bronze_workout/rw/dataset/bpm/',
 'source_format': 'json',
 'header': True,
 'target_catalog': 'dev',
 'target_schema': 'bronze_workout',
 'table_version': 1,
 'target_table': 'bpm',
 'write_mode': 'append',
 'checkpoint_path': '/Volumes/dev/bronze_workout/checkpoints/',
 'merge_key': [],
 'partition_by': [],
 'enabled': True,
 'trigger_mode': 'availableNow',
 'processing_time': '5 minutes',
 'schema_evolution_mode': 'BACKWARD'}

In [6]:
def get_schema_file(path:str):
    df = spark.read.json(path)
    return df.schema

In [7]:
schema = get_schema_file(path=configs_dict["source_path"])
schema

StructType([StructField('key', LongType(), True), StructField('offset', LongType(), True), StructField('partition', LongType(), True), StructField('timestamp', LongType(), True), StructField('topic', StringType(), True), StructField('value', StructType([StructField('device_id', LongType(), True), StructField('heartrate', DoubleType(), True), StructField('time', LongType(), True)]), True)])

In [9]:
ingestion_db = "control"
schema_registry_tb = "schema_registry"

schema_registry_query = f"""CREATE TABLE IF NOT EXISTS {catalog}.{ingestion_db}.{schema_registry_tb} (
  id BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
  table_id INT NOT NULL,
  table_name STRING NOT NULL,
  version INT DEFAULT 1,
  is_latest BOOLEAN DEFAULT TRUE,                 
  schema_format STRING,          
  schema_definition STRING,     
  created_by STRING,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
  )
  TBLPROPERTIES (
    'delta.autoOptimize.autoCompact' = 'true',
    'delta.feature.allowColumnDefaults' = 'supported'
  );

  """

spark.sql(schema_registry_query)

DataFrame[]

In [11]:
spark.table(f"{catalog}.{ingestion_db}.{schema_registry_tb}").show()

+---+--------+----------+-------+---------+-------------+-----------------+----------+----------+
| id|table_id|table_name|version|is_latest|schema_format|schema_definition|created_by|created_at|
+---+--------+----------+-------+---------+-------------+-----------------+----------+----------+
+---+--------+----------+-------+---------+-------------+-----------------+----------+----------+

In [22]:
spark.sql(f"SELECT * FROM {catalog}.{ingestion_db}.{schema_registry_tb}").show(truncate=False)

+---+--------+----------+-------+---------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------------------+
|id |table_id|table_name|version|is_latest|schema_format|schema_definition                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |created_by     |created_at                |
+---+--------+----------+-------+---------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------------------+
|1  |1       |bpm       |1      |true     |json         |{"fields":[{"metadata":{},"name":"key","nullable":true,"type":"long"},{"metadata":{},"name":"offset","nullable":true,"type":"long"},{"metadata":{},"name":"partition","nullable":true,"type":"long"},{"metadata":{},"name":"timestamp","nullable":true,"type":"long"},{"metadata":{},"name":"topic","nullable":true,"type":"string"},{"metadata":{},"name":"value","nullable":true,"type":{"fields":[{"metadata":{},"name":"device_id","nullable":true,"type":"long"},{"metadata":{},"name":"heartrate","nullable":true,"type":"double"},{"metadata":{},"name":"time","nullable":true,"type":"long"}],"type":"struct"}}],"type":"struct"}|gaurav.thagunna|2026-01-27 12:54:10.025041|
+---+--------+----------+-------+---------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------------------+

In [20]:
query = f"""

INSERT INTO {catalog}.{ingestion_db}.{schema_registry_tb} (
  table_id,
  table_name,
  version,
  is_latest,
  schema_format,
  schema_definition,
  created_by
)
VALUES (
  {configs_dict["table_id"]},
  '{configs_dict["target_table"]}',
  1,
  TRUE,
  'json',
  '{schema.json()}',
  'gaurav.thagunna'
)

"""

spark.sql(query)

DataFrame[num_affected_rows: bigint, num_inserted_rows: bigint]

In [24]:
spark.table("dev.control.schema_registry").show(truncate=False)

+---+--------+----------+-------+---------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------------------+
|id |table_id|table_name|version|is_latest|schema_format|schema_definition                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |created_by     |created_at                |
+---+--------+----------+-------+---------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------------------+
|1  |1       |bpm       |1      |true     |json         |{"fields":[{"metadata":{},"name":"key","nullable":true,"type":"long"},{"metadata":{},"name":"offset","nullable":true,"type":"long"},{"metadata":{},"name":"partition","nullable":true,"type":"long"},{"metadata":{},"name":"timestamp","nullable":true,"type":"long"},{"metadata":{},"name":"topic","nullable":true,"type":"string"},{"metadata":{},"name":"value","nullable":true,"type":{"fields":[{"metadata":{},"name":"device_id","nullable":true,"type":"long"},{"metadata":{},"name":"heartrate","nullable":true,"type":"double"},{"metadata":{},"name":"time","nullable":true,"type":"long"}],"type":"struct"}}],"type":"struct"}|gaurav.thagunna|2026-01-27 12:54:10.025041|
+---+--------+----------+-------+---------+-------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+--------------------------+

In [7]:
schema_row = (
    spark.table("dev.control.schema_registry")
         .filter("table_id = 1 AND is_latest = TRUE").limit(1).collect()[0]


)
schema_row

Row(id=1, table_id=1, table_name='bpm', version=1, is_latest=True, schema_format='json', schema_definition='{"fields":[{"metadata":{},"name":"key","nullable":true,"type":"long"},{"metadata":{},"name":"offset","nullable":true,"type":"long"},{"metadata":{},"name":"partition","nullable":true,"type":"long"},{"metadata":{},"name":"timestamp","nullable":true,"type":"long"},{"metadata":{},"name":"topic","nullable":true,"type":"string"},{"metadata":{},"name":"value","nullable":true,"type":{"fields":[{"metadata":{},"name":"device_id","nullable":true,"type":"long"},{"metadata":{},"name":"heartrate","nullable":true,"type":"double"},{"metadata":{},"name":"time","nullable":true,"type":"long"}],"type":"struct"}}],"type":"struct"}', created_by='gaurav.thagunna', created_at=datetime.datetime(2026, 1, 27, 18, 39, 10, 25041))

In [8]:
from pyspark.sql.types import StructType
import json
schema = StructType.fromJson(json.loads(schema_row.schema_definition))
schema

StructType([StructField('key', LongType(), True), StructField('offset', LongType(), True), StructField('partition', LongType(), True), StructField('timestamp', LongType(), True), StructField('topic', StringType(), True), StructField('value', StructType([StructField('device_id', LongType(), True), StructField('heartrate', DoubleType(), True), StructField('time', LongType(), True)]), True)])

In [ ]:
spark.read.json(configs_dict["source_path"]).show(truncate=False)

+------+------+---------+----------+-----+----------------------------------------+
|key   |offset|partition|timestamp |topic|value                                   |
+------+------+---------+----------+-----+----------------------------------------+
|118440|0     |0        |1678410000|bpm  |{118440, 41.21897868284929, 1678410000} |
|118440|1     |1        |1678410001|bpm  |{118440, 46.95949313912609, 1678410001} |
|118440|2     |2        |1678410002|bpm  |{118440, 84.39302961093657, 1678410002} |
|118440|3     |3        |1678410003|bpm  |{118440, 87.4902278952101, 1678410003}  |
|118440|4     |4        |1678410004|bpm  |{118440, 76.16501196545016, 1678410004} |
|118440|5     |5        |1678410005|bpm  |{118440, 42.46430112225653, 1678410005} |
|118440|6     |6        |1678410006|bpm  |{118440, 46.989738006342094, 1678410006}|
|118440|7     |7        |1678410007|bpm  |{118440, 93.72495479825955, 1678410007} |
|118440|8     |8        |1678410008|bpm  |{118440, 85.67159141451009, 1678410008} |
|118440|9     |9        |1678410009|bpm  |{118440, 80.44560147347363, 1678410009} |
|118440|10    |10       |1678410010|bpm  |{118440, 56.13216591424839, 1678410010} |
|118440|11    |11       |1678410011|bpm  |{118440, 45.26557788448558, 1678410011} |
|118440|12    |12       |1678410012|bpm  |{118440, 52.46209602965959, 1678410012} |
|118440|13    |13       |1678410013|bpm  |{118440, 61.489984940645925, 1678410013}|
|118440|14    |14       |1678410014|bpm  |{118440, 52.210181011220534, 1678410014}|
|118440|15    |15       |1678410015|bpm  |{118440, 92.82563798224464, 1678410015} |
|118440|16    |16       |1678410016|bpm  |{118440, 75.48036167165344, 1678410016} |
|118440|17    |17       |1678410017|bpm  |{118440, 59.73514441617856, 1678410017} |
|118440|18    |18       |1678410018|bpm  |{118440, 77.14644565580699, 1678410018} |
|118440|19    |19       |1678410019|bpm  |{118440, 83.34866654655028, 1678410019} |
+------+------+---------+----------+-----+----------------------------------------+
only showing top 20 rows
+------+------+---------+----------+-----+----------------------------------------+
|key   |offset|partition|timestamp |topic|value                                   |
+------+------+---------+----------+-----+----------------------------------------+
|118440|0     |0        |1678410000|bpm  |{118440, 41.21897868284929, 1678410000} |
|118440|1     |1        |1678410001|bpm  |{118440, 46.95949313912609, 1678410001} |
|118440|2     |2        |1678410002|bpm  |{118440, 84.39302961093657, 1678410002} |
|118440|3     |3        |1678410003|bpm  |{118440, 87.4902278952101, 1678410003}  |
|118440|4     |4        |1678410004|bpm  |{118440, 76.16501196545016, 1678410004} |
|118440|5     |5        |1678410005|bpm  |{118440, 42.46430112225653, 1678410005} |
|118440|6     |6        |1678410006|bpm  |{118440, 46.989738006342094, 1678410006}|
|118440|7     |7        |1678410007|bpm  |{118440, 93.72495479825955, 1678410007} |
|118440|8     |8        |1678410008|bpm  |{118440, 85.67159141451009, 1678410008} |
|118440|9     |9        |1678410009|bpm  |{118440, 80.44560147347363, 1678410009} |
|118440|10    |10       |1678410010|bpm  |{118440, 56.13216591424839, 1678410010} |
|118440|11    |11       |1678410011|bpm  |{118440, 45.26557788448558, 1678410011} |
|118440|12    |12       |1678410012|bpm  |{118440, 52.46209602965959, 1678410012} |
|118440|13    |13       |1678410013|bpm  |{118440, 61.489984940645925, 1678410013}|
|118440|14    |14       |1678410014|bpm  |{118440, 52.210181011220534, 1678410014}|
|118440|15    |15       |1678410015|bpm  |{118440, 92.82563798224464, 1678410015} |
|118440|16    |16       |1678410016|bpm  |{118440, 75.48036167165344, 1678410016} |
|118440|17    |17       |1678410017|bpm  |{118440, 59.73514441617856, 1678410017} |
|118440|18    |18       |1678410018|bpm  |{118440, 77.14644565580699, 1678410018} |
|118440|19    |19       |1678410019|bpm  |{118440, 83.34866654655028, 1678410019} |
+------+------+---------+----------+-----+----------------------------------------+
only showing top 20 rows
+------+------+---------+----------+-----+----------------------------------------+
|key   |offset|partition|timestamp |topic|value                                   |
+------+------+---------+----------+-----+----------------------------------------+
|118440|0     |0        |1678410000|bpm  |{118440, 41.21897868284929, 1678410000} |
|118440|1     |1        |1678410001|bpm  |{118440, 46.95949313912609, 1678410001} |
|118440|2     |2        |1678410002|bpm  |{118440, 84.39302961093657, 1678410002} |
|118440|3     |3        |1678410003|bpm  |{118440, 87.4902278952101, 1678410003}  |
|118440|4     |4        |1678410004|bpm  |{118440, 76.16501196545016, 1678410004} |
|118440|5     |5        |1678410005|bpm  |{118440, 42.46430112225653, 1678410005} |
|118440|6     |6        |1678410006|bpm  |{118440, 46.989738006342094, 1678410006}|
|118440|7     |7        |1678410007|bpm  |{118440, 93.72495479825955, 1678410007} |
|118440|8     |8        |1678410008|bpm  |{118440, 85.67159141451009, 1678410008} |
|118440|9     |9        |1678410009|bpm  |{118440, 80.44560147347363, 1678410009} |
|118440|10    |10       |1678410010|bpm  |{118440, 56.13216591424839, 1678410010} |
|118440|11    |11       |1678410011|bpm  |{118440, 45.26557788448558, 1678410011} |
|118440|12    |12       |1678410012|bpm  |{118440, 52.46209602965959, 1678410012} |
|118440|13    |13       |1678410013|bpm  |{118440, 61.489984940645925, 1678410013}|
|118440|14    |14       |1678410014|bpm  |{118440, 52.210181011220534, 1678410014}|
|118440|15    |15       |1678410015|bpm  |{118440, 92.82563798224464, 1678410015} |
|118440|16    |16       |1678410016|bpm  |{118440, 75.48036167165344, 1678410016} |
|118440|17    |17       |1678410017|bpm  |{118440, 59.73514441617856, 1678410017} |
|118440|18    |18       |1678410018|bpm  |{118440, 77.14644565580699, 1678410018} |
|118440|19    |19       |1678410019|bpm  |{118440, 83.34866654655028, 1678410019} |
+------+------+---------+----------+-----+----------------------------------------+
only showing top 20 rows
+------+------+---------+----------+-----+----------------------------------------+
|key   |offset|partition|timestamp |topic|value                                   |
+------+------+---------+----------+-----+----------------------------------------+
|118440|0     |0        |1678410000|bpm  |{118440, 41.21897868284929, 1678410000} |
|118440|1     |1        |1678410001|bpm  |{118440, 46.95949313912609, 1678410001} |
|118440|2     |2        |1678410002|bpm  |{118440, 84.39302961093657, 1678410002} |
|118440|3     |3        |1678410003|bpm  |{118440, 87.4902278952101, 1678410003}  |
|118440|4     |4        |1678410004|bpm  |{118440, 76.16501196545016, 1678410004} |
|118440|5     |5        |1678410005|bpm  |{118440, 42.46430112225653, 1678410005} |
|118440|6     |6        |1678410006|bpm  |{118440, 46.989738006342094, 1678410006}|
|118440|7     |7        |1678410007|bpm  |{118440, 93.72495479825955, 1678410007} |
|118440|8     |8        |1678410008|bpm  |{118440, 85.67159141451009, 1678410008} |
|118440|9     |9        |1678410009|bpm  |{118440, 80.44560147347363, 1678410009} |
|118440|10    |10       |1678410010|bpm  |{118440, 56.13216591424839, 1678410010} |
|118440|11    |11       |1678410011|bpm  |{118440, 45.26557788448558, 1678410011} |
|118440|12    |12       |1678410012|bpm  |{118440, 52.46209602965959, 1678410012} |
|118440|13    |13       |1678410013|bpm  |{118440, 61.489984940645925, 1678410013}|
|118440|14    |14       |1678410014|bpm  |{118440, 52.210181011220534, 1678410014}|
|118440|15    |15       |1678410015|bpm  |{118440, 92.82563798224464, 1678410015} |
|118440|16    |16       |1678410016|bpm  |{118440, 75.48036167165344, 1678410016} |
|118440|17    |17       |1678410017|bpm  |{118440, 59.73514441617856, 1678410017} |
|118440|18    |18       |1678410018|bpm  |{118440, 77.14644565580699, 1678410018} |
|118440|19    |19       |1678410019|bpm  |{118440, 83.34866654655028, 1678410019} |
+------+------+---------+----------+-----+----------------------------------------+
only showing top 20 rows
+------+------+---------+----------+-----+----------------------------------------+
|key   |offset|partition|timestamp |topic|value                                   |
+------+------+---------+----------+-----+----------------------------------------+
|118440|0     |0        |1678410000|bpm  |{118440, 41.21897868284929, 1678410000} |
|118440|1     |1        |1678410001|bpm  |{118440, 46.95949313912609, 1678410001} |
|118440|2     |2        |1678410002|bpm  |{118440, 84.39302961093657, 1678410002} |
|118440|3     |3        |1678410003|bpm  |{118440, 87.4902278952101, 1678410003}  |
|118440|4     |4        |1678410004|bpm  |{118440, 76.16501196545016, 1678410004} |
|118440|5     |5        |1678410005|bpm  |{118440, 42.46430112225653, 1678410005} |
|118440|6     |6        |1678410006|bpm  |{118440, 46.989738006342094, 1678410006}|
|118440|7     |7        |1678410007|bpm  |{118440, 93.72495479825955, 1678410007} |
|118440|8     |8        |1678410008|bpm  |{118440, 85.67159141451009, 1678410008} |
|118440|9     |9        |1678410009|bpm  |{118440, 80.44560147347363, 1678410009} |
|118440|10    |10       |1678410010|bpm  |{118440, 56.13216591424839, 1678410010} |
|118440|11    |11       |1678410011|bpm  |{118440, 45.26557788448558, 1678410011} |
|118440|12    |12       |1678410012|bpm  |{118440, 52.46209602965959, 1678410012} |
|118440|13    |13       |1678410013|bpm  |{118440, 61.489984940645925, 1678410013}|
|118440|14    |14       |1678410014|bpm  |{118440, 52.210181011220534, 1678410014}|
|118440|15    |15       |1678410015|bpm  |{118440, 92.82563798224464, 1678410015} |
|118440|16    |16       |1678410016|bpm  |{118440, 75.48036167165344, 1678410016} |
|118440|17    |17       |1678410017|bpm  |{118440, 59.73514441617856, 1678410017} |
|118440|18    |18       |1678410018|bpm  |{118440, 77.14644565580699, 1678410018} |
|118440|19    |19       |1678410019|bpm  |{118440, 83.34866654655028, 1678410019} |
+------+------+---------+----------+-----+----------------------------------------+
only showing top 20 rows
+------+------+---------+----------+-----+----------------------------------------+
|key   |offset|partition|timestamp |topic|value                                   |
+------+------+---------+----------+-----+----------------------------------------+
|118440|0     |0        |1678410000|bpm  |{118440, 41.21897868284929, 1678410000} |
|118440|1     |1        |1678410001|bpm  |{118440, 46.95949313912609, 1678410001} |
|118440|2     |2        |1678410002|bpm  |{118440, 84.39302961093657, 1678410002} |
|118440|3     |3        |1678410003|bpm  |{118440, 87.4902278952101, 1678410003}  |
|118440|4     |4        |1678410004|bpm  |{118440, 76.16501196545016, 1678410004} |
|118440|5     |5        |1678410005|bpm  |{118440, 42.46430112225653, 1678410005} |
|118440|6     |6        |1678410006|bpm  |{118440, 46.989738006342094, 1678410006}|
|118440|7     |7        |1678410007|bpm  |{118440, 93.72495479825955, 1678410007} |
|118440|8     |8        |1678410008|bpm  |{118440, 85.67159141451009, 1678410008} |
|118440|9     |9        |1678410009|bpm  |{118440, 80.44560147347363, 1678410009} |
|118440|10    |10       |1678410010|bpm  |{118440, 56.13216591424839, 1678410010} |
|118440|11    |11       |1678410011|bpm  |{118440, 45.26557788448558, 1678410011} |
|118440|12    |12       |1678410012|bpm  |{118440, 52.46209602965959, 1678410012} |
|118440|13    |13       |1678410013|bpm  |{118440, 61.489984940645925, 1678410013}|
|118440|14    |14       |1678410014|bpm  |{118440, 52.210181011220534, 1678410014}|
|118440|15    |15       |1678410015|bpm  |{118440, 92.82563798224464, 1678410015} |
|118440|16    |16       |1678410016|bpm  |{118440, 75.48036167165344, 1678410016} |
|118440|17    |17       |1678410017|bpm  |{118440, 59.73514441617856, 1678410017} |
|118440|18    |18       |1678410018|bpm  |{118440, 77.14644565580699, 1678410018} |
|118440|19    |19       |1678410019|bpm  |{118440, 83.34866654655028, 1678410019} |
+------+------+---------+----------+-----+----------------------------------------+
only showing top 20 rows
+------+------+---------+----------+-----+----------------------------------------+
|key   |offset|partition|timestamp |topic|value                                   |
+------+------+---------+----------+-----+----------------------------------------+
|118440|0     |0        |1678410000|bpm  |{118440, 41.21897868284929, 1678410000} |
|118440|1     |1        |1678410001|bpm  |{118440, 46.95949313912609, 1678410001} |
|118440|2     |2        |1678410002|bpm  |{118440, 84.39302961093657, 1678410002} |
|118440|3     |3        |1678410003|bpm  |{118440, 87.4902278952101, 1678410003}  |
|118440|4     |4        |1678410004|bpm  |{118440, 76.16501196545016, 1678410004} |
|118440|5     |5        |1678410005|bpm  |{118440, 42.46430112225653, 1678410005} |
|118440|6     |6        |1678410006|bpm  |{118440, 46.989738006342094, 1678410006}|
|118440|7     |7        |1678410007|bpm  |{118440, 93.72495479825955, 1678410007} |
|118440|8     |8        |1678410008|bpm  |{118440, 85.67159141451009, 1678410008} |
|118440|9     |9        |1678410009|bpm  |{118440, 80.44560147347363, 1678410009} |
|118440|10    |10       |1678410010|bpm  |{118440, 56.13216591424839, 1678410010} |
|118440|11    |11       |1678410011|bpm  |{118440, 45.26557788448558, 1678410011} |
|118440|12    |12       |1678410012|bpm  |{118440, 52.46209602965959, 1678410012} |
|118440|13    |13       |1678410013|bpm  |{118440, 61.489984940645925, 1678410013}|
|118440|14    |14       |1678410014|bpm  |{118440, 52.210181011220534, 1678410014}|
|118440|15    |15       |1678410015|bpm  |{118440, 92.82563798224464, 1678410015} |
|118440|16    |16       |1678410016|bpm  |{118440, 75.48036167165344, 1678410016} |
|118440|17    |17       |1678410017|bpm  |{118440, 59.73514441617856, 1678410017} |
|118440|18    |18       |1678410018|bpm  |{118440, 77.14644565580699, 1678410018} |
|118440|19    |19       |1678410019|bpm  |{118440, 83.34866654655028, 1678410019} |
+------+------+---------+----------+-----+----------------------------------------+
only showing top 20 rows
+------+------+---------+----------+-----+----------------------------------------+
|key   |offset|partition|timestamp |topic|value                                   |
+------+------+---------+----------+-----+----------------------------------------+
|118440|0     |0        |1678410000|bpm  |{118440, 41.21897868284929, 1678410000} |
|118440|1     |1        |1678410001|bpm  |{118440, 46.95949313912609, 1678410001} |
|118440|2     |2        |1678410002|bpm  |{118440, 84.39302961093657, 1678410002} |
|118440|3     |3        |1678410003|bpm  |{118440, 87.4902278952101, 1678410003}  |
|118440|4     |4        |1678410004|bpm  |{118440, 76.16501196545016, 1678410004} |
|118440|5     |5        |1678410005|bpm  |{118440, 42.46430112225653, 1678410005} |
|118440|6     |6        |1678410006|bpm  |{118440, 46.989738006342094, 1678410006}|
|118440|7     |7        |1678410007|bpm  |{118440, 93.72495479825955, 1678410007} |
|118440|8     |8        |1678410008|bpm  |{118440, 85.67159141451009, 1678410008} |
|118440|9     |9        |1678410009|bpm  |{118440, 80.44560147347363, 1678410009} |
|118440|10    |10       |1678410010|bpm  |{118440, 56.13216591424839, 1678410010} |
|118440|11    |11       |1678410011|bpm  |{118440, 45.26557788448558, 1678410011} |
|118440|12    |12       |1678410012|bpm  |{118440, 52.46209602965959, 1678410012} |
|118440|13    |13       |1678410013|bpm  |{118440, 61.489984940645925, 1678410013}|
|118440|14    |14       |1678410014|bpm  |{118440, 52.210181011220534, 1678410014}|
|118440|15    |15       |1678410015|bpm  |{118440, 92.82563798224464, 1678410015} |
|118440|16    |16       |1678410016|bpm  |{118440, 75.48036167165344, 1678410016} |
|118440|17    |17       |1678410017|bpm  |{118440, 59.73514441617856, 1678410017} |
|118440|18    |18       |1678410018|bpm  |{118440, 77.14644565580699, 1678410018} |
|118440|19    |19       |1678410019|bpm  |{118440, 83.34866654655028, 1678410019} |
+------+------+---------+----------+-----+----------------------------------------+
only showing top 20 rows
1.65 s ± 166 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [9]:

df = spark.read.schema(schema).json(configs_dict["source_path"])
df.show(truncate=False)

+------+------+---------+----------+-----+----------------------------------------+
|key   |offset|partition|timestamp |topic|value                                   |
+------+------+---------+----------+-----+----------------------------------------+
|118440|0     |0        |1678410000|bpm  |{118440, 41.21897868284929, 1678410000} |
|118440|1     |1        |1678410001|bpm  |{118440, 46.95949313912609, 1678410001} |
|118440|2     |2        |1678410002|bpm  |{118440, 84.39302961093657, 1678410002} |
|118440|3     |3        |1678410003|bpm  |{118440, 87.4902278952101, 1678410003}  |
|118440|4     |4        |1678410004|bpm  |{118440, 76.16501196545016, 1678410004} |
|118440|5     |5        |1678410005|bpm  |{118440, 42.46430112225653, 1678410005} |
|118440|6     |6        |1678410006|bpm  |{118440, 46.989738006342094, 1678410006}|
|118440|7     |7        |1678410007|bpm  |{118440, 93.72495479825955, 1678410007} |
|118440|8     |8        |1678410008|bpm  |{118440, 85.67159141451009, 1678410008} |
|118440|9     |9        |1678410009|bpm  |{118440, 80.44560147347363, 1678410009} |
|118440|10    |10       |1678410010|bpm  |{118440, 56.13216591424839, 1678410010} |
|118440|11    |11       |1678410011|bpm  |{118440, 45.26557788448558, 1678410011} |
|118440|12    |12       |1678410012|bpm  |{118440, 52.46209602965959, 1678410012} |
|118440|13    |13       |1678410013|bpm  |{118440, 61.489984940645925, 1678410013}|
|118440|14    |14       |1678410014|bpm  |{118440, 52.210181011220534, 1678410014}|
|118440|15    |15       |1678410015|bpm  |{118440, 92.82563798224464, 1678410015} |
|118440|16    |16       |1678410016|bpm  |{118440, 75.48036167165344, 1678410016} |
|118440|17    |17       |1678410017|bpm  |{118440, 59.73514441617856, 1678410017} |
|118440|18    |18       |1678410018|bpm  |{118440, 77.14644565580699, 1678410018} |
|118440|19    |19       |1678410019|bpm  |{118440, 83.34866654655028, 1678410019} |
+------+------+---------+----------+-----+----------------------------------------+
only showing top 20 rows

In [12]:
df.printSchema()

root
 |-- key: long (nullable = true)
 |-- offset: long (nullable = true)
 |-- partition: long (nullable = true)
 |-- timestamp: long (nullable = true)
 |-- topic: string (nullable = true)
 |-- value: struct (nullable = true)
 |    |-- device_id: long (nullable = true)
 |    |-- heartrate: double (nullable = true)
 |    |-- time: long (nullable = true)

In [45]:
configs_dict

{'table_id': 1,
 'source_path': '/Volumes/dev/bronze_workout/rw/dataset/bpm/',
 'source_format': 'json',
 'header': True,
 'target_catalog': 'dev',
 'target_schema': 'bronze_workout',
 'table_version': 1,
 'target_table': 'bpm',
 'write_mode': 'append',
 'checkpoint_path': '/Volumes/dev/bronze_workout/checkpoints/',
 'merge_key': [],
 'partition_by': [],
 'enabled': True,
 'trigger_mode': 'availableNow',
 'processing_time': '5 minutes',
 'schema_evolution_mode': 'BACKWARD'}

In [10]:
from pyspark.sql import SparkSession, DataFrame

def load_date(spark, configs_dict,schema) -> DataFrame:
    """Load data from a given path with the provided schema."""

    return (spark.readStream
            .format("cloudFiles")
            .option("cloudFiles.format", configs_dict["source_format"])
            .option("cloudFiles.schemaLocation", configs_dict["checkpoint_path"]+"schema/"+configs_dict["target_table"])
            .option("cloudFiles.schemaEvolutionMode","rescue")
            .option("cloudFiles.maxFilesPerTrigger", 1)
            .schema(schema)
            .load(configs_dict["source_path"])

    )

In [11]:
raw_data = load_date(spark=spark,configs_dict=configs_dict,schema=schema)

In [12]:
display(raw_data)

AnalysisException: Queries with streaming sources must be executed with writeStream.start(), or from a streaming table or flow definition within a Lakeflow Declarative Pipeline.;
cloudFiles

JVM stacktrace:
org.apache.spark.sql.catalyst.ExtendedAnalysisException
	at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$.throwError(UnsupportedOperationChecker.scala:719)
	at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$.$anonfun$checkForBatch$2(UnsupportedOperationChecker.scala:68)
	at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$.$anonfun$checkForBatch$2$adapted(UnsupportedOperationChecker.scala:65)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:325)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:324)
	at scala.collection.immutable.Vector.foreach(Vector.scala:2125)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$foreachUp$1$adapted(TreeNode.scala:324)
	at scala.collection.immutable.Vector.foreach(Vector.scala:2125)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:324)
	at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$.checkForBatch(UnsupportedOperationChecker.scala:65)
	at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$.checkForBatch(UnsupportedOperationChecker.scala:59)
	at org.apache.spark.sql.execution.QueryExecution.assertSupported(QueryExecution.scala:414)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyWithCachedData$2(QueryExecution.scala:726)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:860)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyWithCachedData$1(QueryExecution.scala:724)
	at scala.util.Try$.apply(Try.scala:217)
	at org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1684)
	at org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1745)
	at org.apache.spark.util.LazyTry.get(LazyTry.scala:75)
	at org.apache.spark.sql.execution.QueryExecution.withCachedData(QueryExecution.scala:734)
	at org.apache.spark.sql.execution.qrc.ResultCacheManager.getResultCacheStats(ResultCacheManager.scala:641)
	at org.apache.spark.sql.connect.execution.SparkConnectPlanExecution.processAsArrowBatches(SparkConnectPlanExecution.scala:228)
	at org.apache.spark.sql.connect.execution.SparkConnectPlanExecution.handlePlan(SparkConnectPlanExecution.scala:136)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handlePlan(ExecuteThreadRunner.scala:385)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:291)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:247)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:536)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:860)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:536)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:124)
	at org.apache.spark.sql.artifact.ArtifactManager.withClassLoaderIfNeeded(ArtifactManager.scala:118)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:123)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:535)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:247)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$execute$1(ExecuteThreadRunner.scala:141)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries(UtilizationMetrics.scala:43)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries$(UtilizationMetrics.scala:40)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.recordActiveQueries(ExecuteThreadRunner.scala:53)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:139)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$2(ExecuteThreadRunner.scala:595)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:104)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:109)
	at scala.util.Using$.resource(Using.scala:296)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:108)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:595)

DataFrame[key: bigint, offset: bigint, partition: bigint, timestamp: bigint, topic: string, value: struct<device_id:bigint,heartrate:double,time:bigint>, _rescued_data: string]

In [13]:
def view_streaming_df(df, num_rows=20, timeout=30):
    """View streaming DataFrame in console"""
    query = (df.writeStream
        .format("console")
        .option("checkpointLocation", f"{configs_dict['checkpoint_path']}tmp/{id(df)}")  # Unique checkpoint
        .option("numRows", num_rows)
        .option("truncate", False)
        .trigger(availableNow=True)
        .start()
    )
    
    query.awaitTermination(timeout=timeout)
    query.stop()
    
    return query

In [14]:
view_streaming_df(df=raw_data, num_rows=20, timeout=30)

In [15]:

# Write to in-memory table
query = (raw_data.writeStream
    .format("memory")
    .queryName("temp_stream_view")  # Name for the temp table
    .option("checkpointLocation", f"{configs_dict['checkpoint_path']}tmp/{id(raw_data)}")  # Unique checkpoint
    .trigger(availableNow=True)
    .start()
)

# Query the in-memory table
spark.sql("SELECT * FROM temp_stream_view LIMIT 10").show()

AnalysisException: This query does not support recovering from checkpoint location. Delete /Volumes/dev/bronze_workout/checkpoints/tmp/4955376272/offsets to start over.

JVM stacktrace:
org.apache.spark.sql.AnalysisException
	at org.apache.spark.sql.errors.QueryCompilationErrors$.recoverQueryFromCheckpointUnsupportedError(QueryCompilationErrors.scala:4518)
	at org.apache.spark.sql.execution.streaming.runtime.ResolveWriteToStream$.resolveCheckpointLocation(ResolveWriteToStream.scala:146)
	at org.apache.spark.sql.execution.streaming.runtime.ResolveWriteToStream$$anonfun$apply$1.applyOrElse(ResolveWriteToStream.scala:52)
	at org.apache.spark.sql.execution.streaming.runtime.ResolveWriteToStream$$anonfun$apply$1.applyOrElse(ResolveWriteToStream.scala:48)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$2(AnalysisHelper.scala:201)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:121)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:201)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:418)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:199)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:195)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:45)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning(AnalysisHelper.scala:102)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning$(AnalysisHelper.scala:99)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsWithPruning(LogicalPlan.scala:45)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators(AnalysisHelper.scala:79)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators$(AnalysisHelper.scala:78)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:45)
	at org.apache.spark.sql.execution.streaming.runtime.ResolveWriteToStream$.apply(ResolveWriteToStream.scala:48)
	at org.apache.spark.sql.execution.streaming.runtime.ResolveWriteToStream$.apply(ResolveWriteToStream.scala:47)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$17(RuleExecutor.scala:510)
	at org.apache.spark.sql.catalyst.rules.RecoverableRuleExecutionHelper.processRule(RuleExecutor.scala:664)
	at org.apache.spark.sql.catalyst.rules.RecoverableRuleExecutionHelper.processRule$(RuleExecutor.scala:648)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.processRule(RuleExecutor.scala:144)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$16(RuleExecutor.scala:510)
	at com.databricks.spark.util.MemoryTracker$.withThreadAllocatedBytes(MemoryTracker.scala:51)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.measureRule(QueryPlanningTracker.scala:350)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$15(RuleExecutor.scala:508)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:200)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$14(RuleExecutor.scala:507)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$13(RuleExecutor.scala:499)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:200)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeBatch$1(RuleExecutor.scala:473)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$23(RuleExecutor.scala:620)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$23$adapted(RuleExecutor.scala:620)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:620)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:200)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:366)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.super$execute(Analyzer.scala:654)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeSameContext$1(Analyzer.scala:654)
	at com.databricks.sql.unity.SAMSnapshotHelper$.visitPlansDuringAnalysis(SAMSnapshotHelper.scala:41)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeSameContext(Analyzer.scala:653)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:626)
	at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:471)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:626)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:543)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:354)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:265)
	at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:354)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.resolveInFixedPoint(HybridAnalyzer.scala:418)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.$anonfun$apply$1(HybridAnalyzer.scala:99)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.withTrackedAnalyzerBridgeState(HybridAnalyzer.scala:136)
	at org.apache.spark.sql.catalyst.analysis.resolver.HybridAnalyzer.apply(HybridAnalyzer.scala:92)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$2(Analyzer.scala:603)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:425)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:603)
	at com.databricks.sql.unity.SAMSnapshotHelper$.visitPlansDuringAnalysis(SAMSnapshotHelper.scala:41)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:592)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$3(QueryExecution.scala:439)
	at com.databricks.spark.util.FrameProfiler$.$anonfun$record$1(FrameProfiler.scala:114)
	at com.databricks.spark.util.FrameProfilerExporter$.maybeExportFrameProfiler(FrameProfilerExporter.scala:200)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:105)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:738)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$8(QueryExecution.scala:961)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withExecutionPhase$1(SQLExecution.scala:161)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:348)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:344)
	at com.databricks.util.TracingSpanUtils$.$anonfun$withTracing$4(TracingSpanUtils.scala:235)
	at com.databricks.util.TracingSpanUtils$.withTracing(TracingSpanUtils.scala:129)
	at com.databricks.util.TracingSpanUtils$.withTracing(TracingSpanUtils.scala:233)
	at com.databricks.tracing.TracingUtils$.withTracing(TracingUtils.scala:296)
	at com.databricks.spark.util.DatabricksTracingHelper.withSpan(DatabricksSparkTracingHelper.scala:112)
	at com.databricks.spark.util.DBRTracing$.withSpan(DBRTracing.scala:47)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionPhase(SQLExecution.scala:142)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$7(QueryExecution.scala:961)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1620)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$5(QueryExecution.scala:954)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$4(QueryExecution.scala:951)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$3(QueryExecution.scala:951)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:950)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution.withQueryExecutionId(QueryExecution.scala:938)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:949)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:860)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:948)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$2(QueryExecution.scala:421)
	at com.databricks.sql.util.MemoryTrackerHelper.withMemoryTracking(MemoryTrackerHelper.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$lazyAnalyzed$1(QueryExecution.scala:420)
	at scala.util.Try$.apply(Try.scala:217)
	at org.apache.spark.util.Utils$.doTryWithCallerStacktrace(Utils.scala:1684)
	at org.apache.spark.util.Utils$.getTryWithCallerStacktrace(Utils.scala:1745)
	at org.apache.spark.util.LazyTry.get(LazyTry.scala:75)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:481)
	at org.apache.spark.sql.classic.StreamingQueryManager.createQuery(StreamingQueryManager.scala:417)
	at org.apache.spark.sql.classic.StreamingQueryManager.startQuery(StreamingQueryManager.scala:523)
	at org.apache.spark.sql.classic.streaming.startQuery(DataStreamWriter.scala:475)
	at org.apache.spark.sql.classic.streaming.startInternal(DataStreamWriter.scala:381)
	at org.apache.spark.sql.classic.streaming.start(DataStreamWriter.scala:179)
	at org.apache.spark.sql.classic.streaming.start(DataStreamWriter.scala:71)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.handleWriteStreamOperationStart(SparkConnectPlanner.scala:4390)
	at org.apache.spark.sql.connect.planner.SparkConnectPlanner.process(SparkConnectPlanner.scala:3492)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.handleCommand(ExecuteThreadRunner.scala:394)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1(ExecuteThreadRunner.scala:290)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$executeInternal$1$adapted(ExecuteThreadRunner.scala:247)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$2(SessionHolder.scala:536)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:860)
	at org.apache.spark.sql.connect.service.SessionHolder.$anonfun$withSession$1(SessionHolder.scala:536)
	at org.apache.spark.JobArtifactSet$.withActiveJobArtifactState(JobArtifactSet.scala:97)
	at org.apache.spark.sql.artifact.ArtifactManager.$anonfun$withResources$1(ArtifactManager.scala:124)
	at org.apache.spark.sql.artifact.ArtifactManager.withClassLoaderIfNeeded(ArtifactManager.scala:118)
	at org.apache.spark.sql.artifact.ArtifactManager.withResources(ArtifactManager.scala:123)
	at org.apache.spark.sql.connect.service.SessionHolder.withSession(SessionHolder.scala:535)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.executeInternal(ExecuteThreadRunner.scala:247)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.$anonfun$execute$1(ExecuteThreadRunner.scala:141)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries(UtilizationMetrics.scala:43)
	at com.databricks.spark.connect.service.UtilizationMetrics.recordActiveQueries$(UtilizationMetrics.scala:40)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.recordActiveQueries(ExecuteThreadRunner.scala:53)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner.org$apache$spark$sql$connect$execution$ExecuteThreadRunner$$execute(ExecuteThreadRunner.scala:139)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.$anonfun$run$2(ExecuteThreadRunner.scala:595)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at com.databricks.unity.UCSEphemeralState$Handle.runWith(UCSEphemeralState.scala:51)
	at com.databricks.unity.HandleImpl.runWith(UCSHandle.scala:104)
	at com.databricks.unity.HandleImpl.$anonfun$runWithAndClose$1(UCSHandle.scala:109)
	at scala.util.Using$.resource(Using.scala:296)
	at com.databricks.unity.HandleImpl.runWithAndClose(UCSHandle.scala:108)
	at org.apache.spark.sql.connect.execution.ExecuteThreadRunner$ExecutionThread.run(ExecuteThreadRunner.scala:595)

In [ ]:
table = ingest_table_registry

CREATE TABLE IF NOT EXISTS control.ingest_table_registry (
  id INT,
  source_path STRING,
  source_format STRING,
  header BOOLEAN,
  table_id STRING,
  table_version INT,
  merge_key STRING,
  partition_by STRING,
  target_catalog STRING,
  target_schema STRING,
  target_table STRING,
  write_mode STRING,             -- append|merge|overwrite
  checkpoint_path STRING,
  enabled BOOLEAN,
  trigger_mode STRING,           -- availableNow | processingTime
  processing_time STRING,        -- "5 seconds"
  sla_hours INT,
  priority INT,
  expected_rows_per_day BIGINT,
  schema_compatibility STRING,   -- BACKWARD|FORWARD|FULL|NONE
  last_success TIMESTAMP,
  last_error STRING,
  consecutive_failures INT,
  last_run_duration_seconds INT,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
)
USING DELTA;

In [ ]:
CREATE TABLE control.bronze_tables (
  table_name STRING,
  source_path STRING,
  format STRING,
  header BOOLEAN,
  schema_id STRING,
  merge_key STRING,
  partition_by STRING,
  enabled BOOLEAN,
  trigger_mode STRING,       
  processing_time STRING,  
  owner STRING,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
)
USING DELTA;

DataFrame[]

In [18]:
!pwd

/Users/adi/Library/CloudStorage/OneDrive-UltraTendencyInternationalGmbH/Databricks/real_projects/WorkoutTime_Analytics_Databricks/notebooks